name: Dungeons
version: ${project.version}
main: net.plasmere.dungeons.Dungeons
api-version: 1.8
authors: [ Nitrate, tomstar ]
description: Dungeon runner plugin.
website: https://site.plasmere.net

commands:
  test:
    permission: "dungeons.admin"
    aliases: "testspawn"
  addenchantments:
    permission: "dungeons.admin"
    aliases: "addench"
  saveschem:
    permission: "dungeons.admin"
    aliases: "saveschematic"
